### ISSUE TITLE
when pod install happens the generated binaries/frameworks are universal? if not then how can I make sure that they are universal.

### ISSUE THREAD

**Issue by atelaich** [leavez/cocoapods-binary#102]
Thanks for your feedback!

If it's a bug:

- What's your environment:
  - run ` pod env | egrep 'CocoaPods |Xcode|cocoapods-binary' ` then paste the result here 
- A demo project is helpful:
  - It will be very helpful if provides a demo project that reproduce the problem. A blank project with cocoapods-binary can be downloaded [here](https://github.com/leavez/cocoapods-binary/files/3086250/BinaryDemo.zip), which can be remodeled to a minimal problematic environment. Attach the demo.zip to the comments.

**Comment by sueLan** [comment]
Yes, it generates `Macho-universal binary` , containing instructions for ` x86_64`  `armv7` `arm64` .  This is very good. We can use it in both simulator and physical devices. 
https://github.com/leavez/cocoapods-binary/blob/04c02f8d1aeabf052c776fafa5a07bfa9ad29657/lib/cocoapods-binary/rome/build_framework.rb#L53

We can use  `lipo -info` to check the file in the `_Prebuild/GeneratedFrameworks/A/A.framework/A 

```
lipo -info A
Architectures in the fat file: BinaryA are: x86_64 armv7 arm64
```

**Comment by atelaich** [comment]
Thanks @sueLan
