### ISSUE TITLE
How to handle sub-libraries in a library

### ISSUE THREAD

**Issue by Agenric** [leavez/cocoapods-binary#22]
When i use `cocoapods-binary`, i found that some libraries with sub-libraries only generate one main framework after binary.
like this:
![image](https://user-images.githubusercontent.com/11513056/39698906-5da9325c-5229-11e8-9c5d-359b3d70fd6c.png)

Does this situation affect the project?

**Comment by leavez** [comment]
It's not a problem.Only one framework will be generated for a pod. All sub-pods will be compiled and linked into the main framework, i.e. the `AFNetworking.framework` in your case. Open the framework, and you will find the `AFNetworkReachabilityManager.h` of the Reachability, and others things.

What's more: If you only specify a sub-pod, e.g. `pod 'AFNetworking/Reachability'`, it will also generate a framework named `AFNetworking.framework` and contain only the content of `AFNetworking/Reachability`
