### ISSUE TITLE
How can I trigger it in podspec-dependency

### ISSUE THREAD

**Issue by Scyano** [leavez/cocoapods-binary#24]
```
#.podspec

s.dependency = 'Alamofire'
```

**Comment by leavez** [comment]
Let A have dependency pod B. B will be in prebuilt form if A is in prebuilt form, which means A is marked binary in Podfile.

If A is not marked binary, e.g. local pods or manually turn off, you can specify B explicitly in Podfile:

```ruby
# podfile
pod 'A', :binary => false  # manually set A to source code
pod 'B', :binary => true  # B will be in form of prebuilt framework

```
