### ISSUE TITLE
Comparison with Rome

### ISSUE THREAD

**Issue by paulb777** [leavez/cocoapods-binary#31]
This looks awesome!

Would you update the README with a comparison with [Rome](https://github.com/CocoaPods/Rome)?

**Comment by leavez** [comment]
**Goal of Rome:** 
Generate a list of framework files.

**Goal of cococapods-binary:**
The plugin doesn't affect the way using cocoapods. Do a `pod install`, get the workspace file and develop in your old way. The only difference is that every pod target just import a framework file and no source code file.

In fact, cococapods-binary also use some code of Rome to build the framework files.
