### ISSUE TITLE
transitive dependencies missing

### ISSUE THREAD

**Issue by nebiros** [leavez/cocoapods-binary#36]
At my `Podfile`, I have this pod:

```
pod "PusherSwift"
```

It's podspec had some other dependencies: https://github.com/pusher/pusher-websocket-swift/blob/master/PusherSwift.podspec, so, I got this error from Xcode importing `PusherSwift` pod:

```
Missing required modules: 'CryptoSwift', 'Starscream', 'TaskQueue'
```

**Comment by leavez** [comment]
@nebiros I didn't reproduce this bug. It works fine for me. What's your cocoapods version? Could you provide a demo please?

<img width="723" alt="image" src="https://user-images.githubusercontent.com/4454541/54631307-b0123f80-4ab6-11e9-914e-a598fab0d96d.png">

**Comment by nebiros** [comment]
@leavez I try it again, newest version, 0.4.3, everything is working fine, :)
