### ISSUE TITLE
Your Podfile requires that the plugin `cocoapods-binary` be installed

### ISSUE THREAD

**Issue by mrdavenz** [leavez/cocoapods-binary#43]
If I run it by the book on my macbook pro, with Ruby 2.3.0 installed, I get```[!] Your Podfile requires that the plugin `cocoapods-binary` be installed. Please install it and try installation again.```

Is there something undocumented that the average user should be privy to, in order to get this going?

**Comment by leavez** [comment]
`gem install cocoapods-binary` ?

**Comment by X140Yu** [comment]
Hi @mrdavenz , is your project gems managed by `Gemfile`? If it's so, you should add `gem 'cocoapods-binary'` to your project's `Gemfile`.

**Comment by liuxingIphone** [comment]
i have installed succeed. when "pod install",  I get[!] Your Podfile requires that the plugin `cocoapods-binary` be installed. Please install it and try installation again.

**Comment by poojagaonkar** [comment]
@liuxingIphone did you find a solution for this?

**Comment by a4xopen** [comment]
sudo gem install cocoapods cocoapods-binary
sudo gem install -n /usr/local/bin  cocoapods cocoapods-binary

**Comment by cristipaval** [comment]
> i have installed succeed. when "pod install", I get[!] Your Podfile requires that the plugin `cocoapods-binary` be installed. Please install it and try installation again.

I run `source ~/.zshrc` after the installation and then it worked

**Comment by youssef-lr** [comment]
Thanks @cristipaval, worked for me 😄
