### ISSUE TITLE
Unclear documentation on dSYM issue

### ISSUE THREAD

**Issue by grigorye** [leavez/cocoapods-binary#44]
It would be great if the following:

> dSYM files is missing for dynamic frameworks using this plugin. Walkaround: Don't use this plugin for a release build. Add a if condition with ENV around plugin 'cocoapods-binary'

would have a real receipt in terms of Podfile. Still can't figure it out, sorry...

**Comment by leavez** [comment]
In your podfile
```
if not ENV['DISABLE_POD_BINARY'] == 'true'
    plugin 'cocoapods-binary'
end
```

Before your release building. In the command line:
```
export DISABLE_POD_BINARY=true
pod install
```
Then the plugin will not be used for this pod install.

**Comment by grigorye** [comment]
Got it, thank you very much! Is there a way to avoid pod install when switching between release and debug? We store pods in git, and would like to avoid pod install unless there’s a change in pod configuration. I wonder if there’s a workaround... Like using two Pods directories or two integration workspaces, or something like that...

Btw,  is this whole thing (dSYM) a temporary  issue or “by design”?

**Comment by leavez** [comment]
Just a temporary issue that haven't been handled. 😂

**Comment by leavez** [comment]
https://github.com/leavez/cocoapods-binary/pull/48

**Comment by Akshay-1Mg** [comment]
How I can maintain pre-compiled pods for bev build and static/(pods with source) for release builds simultaneously ??
