### ISSUE TITLE
[!] Attempt to read non existent folder `/Users/ian/code/tt/ios/Pods/GCDWebServer`.

### ISSUE THREAD

**Issue by ileitch** [leavez/cocoapods-binary#56]
I'm using

```
plugin 'cocoapods-binary'
all_binary!
keep_source_code_for_prebuilt_frameworks!
```

Except for `pod 'GCDWebServer', binary: false`.

The prebuild step correctly ignores `GCDWebServer`, however the pod install step fails with:
```
[!] Attempt to read non existent folder '/Users/ian/code/tt/ios/Pods/GCDWebServer'.
```

Prior to this error I do see `Installing GCDWebServer (3.4.2)` from the pod install step though.

Any idea what's causing this?

P.S I'm using `binary: false` for `GCDWebServer` since we need to include its header files in a bridging header.

**Comment by gerbil802** [comment]
+1

**Comment by leavez** [comment]
I tried it with a blank project, it works fine. 

Google 'Attempt to read non existent folder' shows many similar problems, such as https://github.com/BoltsFramework/Bolts-ObjC/issues/66 and https://stackoverflow.com/questions/24385329/attempt-to-read-non-existent-folder-private-tmp-cocoapods-lint-pods, so I doesn't think it's a bug of the plugin.

The log 'Installing GCDWebServer (3.4.2)' is printed before any actual download action.

**Comment by ileitch** [comment]
It works fine without the plugin, so while it may not directly be a bug in the plugin, it's clearly an issue that's been triggered somehow by this plugin.
