### ISSUE TITLE
Swift header file not created correctly when building with Xcode 10.2

### ISSUE THREAD

**Issue by Alexs1987** [leavez/cocoapods-binary#58]
Swift 5 seems to have changed the format of the generated Swift header file by adding the following conditionals dependent on the architecture:

```
#if 0
#elif defined(__arm64__) && __arm64__
...
#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
...
```
When building the iOS platform with cocoapods-binary the generated Swift header file only has `__arm64__ `and `__ARM_ARCH_7A__` but does not have any conditionals for the simulator architectures and therefore the Swift parts of the framework can't be used by Objective C code in the app.

Similar issue in Carthage - https://github.com/Carthage/Carthage/issues/2718

**Comment by leavez** [comment]
fixed
