### ISSUE TITLE
Binary doesn't support pods who integrate in 2 or more platforms simultaneously

### ISSUE THREAD

**Issue by pepejeria** [leavez/cocoapods-binary#64]
```
CocoaPods : 1.6.1
Xcode : 10.1 (10B61)
cocoapods-binary      : 0.4.3
```

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-binary'
platform :ios, '11.2'
use_frameworks!
inhibit_all_warnings!

target 'AnimalHouse' do
  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # Firebase
  pod 'Firebase/Core', :binary => true
  pod 'Firebase/Firestore', :binary => true
  pod 'Firebase/Auth', :binary => true
  pod 'CodableFirebase'
end

target 'AnimalHouseFirestoreContractTests' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxBlocking'

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'CodableFirebase'
end

target 'AnimalHouseHttpContractTests' do
  pod 'RxSwift'
  pod 'RxCocoa'
  
  pod 'RxBlocking'
end

target 'RoadTripTests' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  pod 'RxTest'
  pod 'RxBlocking'
end


target 'AnimalHouseTestsHostApplication' do
end

target 'AnimalHouseFirestoreContractTestsHostApplication' do
end
```

The following app has two test targets running on separate host apps called `AnimalHouseTestsHostApplication` and `AnimalHouseFirestoreContractTestsHostApplication `. I get the following error when running `pod install`:

`[!] Binary doesn't support pods who integrate in 2 or more platforms simultaneously: ["Firebase"]`

**Comment by leavez** [comment]
It's a limitation for now. Works as expect.  

Workaround: turn off binary for Firebase, for both platforms.

I do have plan to improve it in future version, but no guarantee. At least it won't be on next major version.

**Comment by pepejeria** [comment]
Hi, thank you for getting back to me. What do you mean with “for both platforms”? Only iOS has been defined in the Podfile. Thanks

**Comment by leavez** [comment]
Sorry for my negligent. The correct answer:

The plugin didn’t give enough log info. The  limitation is that one pod should have only one target in the workspace. If a pod exists in 2 different platform targets, it will have 2 targets in the Pod project. Fail. If a pod have different subspecs in different targets, 2 targets containing different content will be generated in the Pod project. Fail, too.

**Comment by leavez** [comment]
@pepejeria You encountered the second case. If you still want to use binary for Firebase, set the same subspecs of Firebase for main and test targets.

**Comment by pepejeria** [comment]
Yeah, that works. I set the same subspaces for all targets and pod install works. 

`xcodebuild` fails though 
```
[20:27:50]: ▸ ❌  /Users/me//FirebaseConfiguration.swift:2:8: could not build Objective-C module 'Firebase'
```

**Comment by leavez** [comment]
Added mote detail.  Close the issue temporarily. Wish to solve it completely in the following major version.
