### ISSUE TITLE
cocoapods-binary doesn't work for me

### ISSUE THREAD

**Issue by owenzhao** [leavez/cocoapods-binary#66]
Here is the logs.

$ pod install
🚀  Prebuild frameworks
Analyzing dependencies
Downloading dependencies
Using Realm (3.14.1)
Using RealmSwift (3.14.1)
Using SnapKit (4.0.1)
Generating Pods project
Sending stats

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : edu-git-cocoapods-specs - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ 0ea7e62cafe6cebaca5212f428be41d32e4e0ab7
               master - https://github.com/CocoaPods/Specs.git @ 93a87776d510603f6f99f54be6f180f579b75c82
```

### Plugins

```
cocoapods-binary      : 0.4.3
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
plugin 'cocoapods-binary'

target 'iOS Post 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '11.0'
  use_frameworks!

  # Pods for iOS Post 2
  pod 'RealmSwift', :binary => true
  pod 'SnapKit', '~> 4.0.0', :binary => true

end

target 'iOS Poster 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '11.0'
  use_frameworks!

  # Pods for iOS Poster 2
  pod 'RealmSwift', :binary => true
  pod 'SnapKit', '~> 4.0.0', :binary => true

end

# target 'iOS SharingAPI' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for iOS SharingAPI
#
# end

target 'Post 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :osx, '10.13'
  use_frameworks!

  # Pods for Post 2
  pod 'RealmSwift', :binary => true

end

target 'Poster 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :osx, '10.13'
  use_frameworks!

  # Pods for Poster 2
  pod 'RealmSwift', :binary => true

end

# target 'SharingAPI' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for SharingAPI
#
# end
#
target 'Today Post 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :osx, '10.13'
  use_frameworks!

  # Pods for Today Post 2
  pod 'RealmSwift', :binary => true

end
#
# target 'Watch Poster 2' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for Watch Poster 2
#
# end
#
target 'Watch Poster 2 Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :watchos, '4.0'
  use_frameworks!

  # Pods for Watch Poster 2 Extension
  pod 'RealmSwift'

end
#
# target 'watchos SharingAPI' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for watchos SharingAPI
#
# end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '3.0'
        end
    end
end
```

### Error

```
NoMethodError - undefined method `recursive_dependent_targets' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.3/lib/cocoapods-binary/Prebuild.rb:105:in `block in prebuild_frameworks!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.3/lib/cocoapods-binary/Prebuild.rb:105:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.3/lib/cocoapods-binary/Prebuild.rb:105:in `prebuild_frameworks!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.3/lib/cocoapods-binary/Prebuild.rb:219:in `block in <class:Installer>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:476:in `perform_post_install_actions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:145:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.3/lib/cocoapods-binary/Main.rb:103:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:468:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:159:in `block in prepare'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:155:in `prepare'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:135:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60recursive_dependent_targets%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:91:in `block in validate_delegate': #<Pod::UserInterface::InspectorReporter:0x00007fddc109a190> does not handle inspector_successfully_recieved_report (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:90:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:90:in `validate_delegate'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:20:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
iMac5K:Poster 2 zhaoxin$ gems 
-bash: gems: command not found
iMac5K:Poster 2 zhaoxin$ gem 
RubyGems is a sophisticated package manager for Ruby.  This is a
basic help message containing pointers to more information.

  Usage:
    gem -h/--help
    gem -v/--version
    gem command [arguments...] [options...]

  Examples:
    gem install rake
    gem list --local
    gem build package.gemspec
    gem help install

  Further help:
    gem help commands            list all 'gem' commands
    gem help examples            show some examples of usage
    gem help gem_dependencies    gem dependencies file guide
    gem help platforms           gem platforms guide
    gem help <COMMAND>           show help on COMMAND
                                   (e.g. 'gem help install')
    gem server                   present a web page at
                                 http://localhost:8808/
                                 with info about installed gems
  Further information:
    http://guides.rubygems.org

**Comment by leavez** [comment]
Although I didn't reproduce the crash, I found an unsupported case for this plugin in your podfile, which may lead this crash. v0.4.4 add more detail log for this. Please try it.

**Comment by owenzhao** [comment]
It seems I encountered another issue after updating to v0.4.4. I think it is quit common that there are targets containing the same pod. Even if I just develop an iOS app, I probably have to use the same pod if I want to make a Share Extension or Today Extension targets.

----------------below is command line-----------------

pod update
Update all pods
🚀  Prebuild frameworks
Updating local specs repositories
        $ /usr/bin/git -C
        /Users/zhaoxin/.cocoapods/repos/edu-git-cocoapods-specs fetch origin
        --progress
        remote: Counting objects: 10707, done.        
        remote: Compressing objects: 100% (4893/4893), done.        
        remote: Total 10707 (delta 5727), reused 9219 (delta 5416)        
        Receiving objects: 100% (10707/10707), 1.87 MiB | 5.09 MiB/s, done.
        Resolving deltas: 100% (5727/5727), done.
        From https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs
           0ea7e62cafe..cbe0e776e2a  master     -> origin/master
        $ /usr/bin/git -C
        /Users/zhaoxin/.cocoapods/repos/edu-git-cocoapods-specs rev-parse
        --abbrev-ref HEAD
        master
        $ /usr/bin/git -C
        /Users/zhaoxin/.cocoapods/repos/edu-git-cocoapods-specs reset --hard
        origin/master
        HEAD is now at cbe0e776e2a [Add] Bugsee 1.21.4
Analyzing dependencies
Downloading dependencies
Installing Realm 3.14.2 (was 3.14.1)
Installing RealmSwift 3.14.2 (was 3.14.1)
Using SnapKit (4.0.1)
Generating Pods project
Sending stats
[!] Oops, you came across a limitation of cocoapods-binary.

The plugin requires that one pod should have ONLY ONE target in the 'Pod.xcodeproj'. There are mainly 2 situations causing this problem:

1. One pod integrates in 2 or more different platforms' targets. e.g.
    ```
    target 'iphoneApp' do
      pod 'A', :binary => true
    end
    target 'watchApp' do
      pod 'A'
    end
    ```

2. Use different subspecs in multiple targets. e.g.
    ```
    target 'iphoneApp' do
      pod 'A/core'
      pod 'A/network'
    end
    target 'iphoneAppTest' do
      pod 'A/core'
    end
    ```

Related pods: ["Realm", "RealmSwift", "Realm", "RealmSwift"], target names: ["Realm-iOS", "RealmSwift-iOS", "Realm-macOS", "RealmSwift-macOS"]

**Comment by leavez** [comment]
It's a goal of next major version. I'm doing it.

**Comment by nex-derek** [comment]
Hi, wondering if it is fixed?

**Comment by LeonidKokhnovich** [comment]
@leavez Hi! Thanks a lot for supporting the project! 
I wonder if you know what needs to be done in order to support
```
target 'iphoneApp' do
  pod 'A', :binary => true
end
target 'watchApp' do
  pod 'A'
end
```
use case?

**Comment by owenzhao** [comment]
I have't tested yet. If anyone interested, you can try "generate_multiple_pod_projects" and see if that works with this project.

**Comment by LeonidKokhnovich** [comment]
@owenzhao Thanks! I have tried inserting the following config
```
install! 'cocoapods', :generate_multiple_pod_projects => true
```
to my Podfile, but I still see the same issue:
___
[!] Oops, you came across a limitation of cocoapods-binary.

The plugin requires that one pod should have ONLY ONE target in the 'Pod.xcodeproj'. There are mainly 2 situations causing this problem:

1. One pod integrates in 2 or more different platforms' targets. e.g.
    ```
    target 'iphoneApp' do
      pod 'A', :binary => true
    end
    target 'watchApp' do
      pod 'A'
    end
    ```

2. Use different subspecs in multiple targets. e.g.
    ```
    target 'iphoneApp' do
      pod 'A/core'
      pod 'A/network'
    end
    target 'iphoneAppTest' do
      pod 'A/core'
    end
    ```
___
Deintegrating pod didn't help. Any other idea what could be done to support 
    ```
    target 'iphoneApp' do
      pod 'A', :binary => true
    end
    target 'tvOSApp' do
      pod 'A', :binary => true
    end
    ```

**Comment by owenzhao** [comment]
> @owenzhao Thanks! I have tried inserting the following config
> 
> ```
> install! 'cocoapods', :generate_multiple_pod_projects => true
> ```
> 
> to my Podfile, but I still see the same issue:
> 
> [!] Oops, you came across a limitation of cocoapods-binary.
> 
> The plugin requires that one pod should have ONLY ONE target in the 'Pod.xcodeproj'. There are mainly 2 situations causing this problem:
> 
> 1. One pod integrates in 2 or more different platforms' targets. e.g.
>    ```
>    target 'iphoneApp' do
>      pod 'A', :binary => true
>    end
>    target 'watchApp' do
>      pod 'A'
>    end
>    ```
> 2. Use different subspecs in multiple targets. e.g.
>    ```
>    target 'iphoneApp' do
>      pod 'A/core'
>      pod 'A/network'
>    end
>    target 'iphoneAppTest' do
>      pod 'A/core'
>    end
>    ```
> 
> Deintegrating pod didn't help. Any other idea what could be done to support
> `target 'iphoneApp' do pod 'A', :binary => true end target 'tvOSApp' do pod 'A', :binary => true end`

Maybe the new issue is easier to fix than the old one. For me, the new error messages mean that 'cocoapods-binary' doesn't support "generate_multiple_pod_projects" feature.

**Comment by planecore** [comment]
Did someone found a solution for multiple projects?
