### ISSUE TITLE
无法生成二进制文件求解

### ISSUE THREAD

**Issue by zhangjianbin** [leavez/cocoapods-binary#80]
pod 'YBHomeKit',  :path=>'../Internal/MiHomeKit',  :binary => true
这种写法好像无法生成对应的二进制文件，是不支持本地私有的这种pod形式吗

**Comment by X140Yu** [comment]
https://github.com/leavez/cocoapods-binary/issues/33

**Comment by zhangjianbin** [comment]
能不能支持一下本地私有库也可以切换源码跟二进制。好多场景下有这样的需求。
