### ISSUE TITLE
[Question] Does `binary` here means dynamic framework?

### ISSUE THREAD

**Issue by allenlinli** [leavez/cocoapods-binary#90]
As title.
Sorry I am confused with the term here, even though you mentioned static framework.

**Comment by ajjnix** [comment]
@allenlinli `binary` is just mean that your code is compiled in framework. Framework can be static or dynamic but this is about another.
In cocoapods you can set mach-type to static or dynamic before cocoapods-binary will start prebuild phase.

**Comment by allenlinli** [comment]
I think you mean `binary` can be either `dynamic framework` or `static framework`. I was confused since it wasn't `cocoapods-framework`. But I got it now, thank you @ajjnix .
